// <auto-generated />
using ExsysmaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExsysmaAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250402003204_mudancaClasses")]
    partial class mudancaClasses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ExsysmaAPI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ExsysmaAPI.Models.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalVariableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoalVariableValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GoalVariableId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("ExsysmaAPI.Models.Variable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGoalVariable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Values")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Variables");
                });

            modelBuilder.Entity("ExsysmaAPI.Models.Rule", b =>
                {
                    b.HasOne("ExsysmaAPI.Models.Variable", "GoalVariable")
                        .WithMany()
                        .HasForeignKey("GoalVariableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExsysmaAPI.Models.Project", "Project")
                        .WithMany("Rules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalVariable");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ExsysmaAPI.Models.Variable", b =>
                {
                    b.HasOne("ExsysmaAPI.Models.Project", "Project")
                        .WithMany("Variables")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ExsysmaAPI.Models.Project", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("Variables");
                });
#pragma warning restore 612, 618
        }
    }
}
